name: Despliegue continuo a GitHub Pages

#  CUNDO se ejecutar谩
on:
  push:
    branches: [ "main" ]   # Cada vez que hagas commit a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # Entorno virtual de ejecuci贸n

    steps:
      # 1锔 Descargar tu c贸digo
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      # 2锔 Instalar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3锔 Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      # 4锔 Ejecutar pruebas
       # name: Ejecutar pruebas
         # run: npm test

      # 5锔 Generar build de producci贸n
      - name: Generar build de producci贸n
        run: npm run build

      # 6锔 Desplegar autom谩ticamente en GitHub Pages
      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./


